# Generated by Django 2.2.4 on 2020-11-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductCostView',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'invent_SupplierProductCostView',
                'managed': False,
            },
        ),
    ]
